name: astronomia
description: >-
  Astronomical algorithms in Dart — positions of Sun, Moon, and planets,
  eclipses, phases, coordinates, magnitudes, and more. Based on Jean Meeus's
  "Astronomical Algorithms".
version: 1.1.0
repository: https://github.com/dmvvilela/astronomia
homepage: https://github.com/dmvvilela/astronomia
topics:
  - astronomy
  - science
  - math
  - calendar

environment:
  sdk: ^3.11.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
